
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
// #include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\DDS\DDS.h"

// -*-*- List of node objects -*-*-
nBlock_DDS             nb_nBlockNode0_DDS        (p5, p7, p14, 40000);

// -*-*- List of connection objects -*-*-


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
